// <auto-generated />
namespace StudentRegistarationPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Addingtheusertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingtheusertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202406240330447_Adding the user table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
